# Generated by Django 3.1.1 on 2020-09-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyAPIS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=240, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relation', models.CharField(blank=True, max_length=240, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='relatives',
            field=models.ManyToManyField(blank=True, related_name='family_member', to='FamilyAPIS.FamilyMember'),
        ),
    ]
