# Generated by Django 3.1.1 on 2020-09-19 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyAPIS', '0002_auto_20200919_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
